name: build-test
on: [pull_request, push]

jobs:
  always_skip:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy step
        run: echo "This job is always skipped"
    if: false

#  always_fail:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Dummy step
#        run: exit 1

  always_success:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy step
        run: echo "This job is always successful"

  slack-notice-action:
    runs-on: ubuntu-latest
    if: always()
    needs: [always_skip, always_success]
    steps:
      - run: |
          RESULTS=$(echo '${{ toJSON(needs) }}' | jq -r '. | to_entries[] | .value.result')
          RESULTS=$(printf "${RESULTS}" | tr -d '"')
          echo "${RESULTS}" > results.txt
          all_success="true"
          while IFS= read -r result; do
            if [[ "$result" != "success" && "$result" != "skipped" ]]; then
              all_success="false"
              echo "job_result:${result}"
              break
            fi
            echo "job_result:${result}"
          done < results.txt

          if [[ "$all_success" == "true" ]]; then
            echo "All jobs have either succeeded or been skipped!"
            echo "WORKFLOW_CONCLUSION=success" >> $GITHUB_ENV
          else
            echo "Some jobs did not succeed or were not skipped."
            echo "WORKFLOW_CONCLUSION=failure" >> $GITHUB_ENV
          fi

      - uses: sonots/slack-notice-action@v3
        with:
          status: ${{ env.WORKFLOW_CONCLUSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
